### ISSUE TITLE
requests returning empty data or undefined

### ISSUE THREAD

**Issue by chuckreynolds** [UltiRequiem/joke-api#26]
Examples w/ have empty response
- https://joke.deno.dev/type/general/1
- https://joke.deno.dev/type/programming
- https://joke.deno.dev/2

returns undefined
- https://joke.deno.dev/id/425

**Comment by UltiRequiem** [comment]
Everything is working now, I updated the API endpoints, so make sure to re-read the readme 🐌

Thanks for making the issue ✨

**Comment by chuckreynolds** [comment]
> Everything is working now, I updated the API endpoints, so make sure to re-read the readme 🐌
> 

Is there no limiter function anymore? like to grab only one randomly from a type?

**Comment by UltiRequiem** [comment]
> > Everything is working now, I updated the API endpoints, so make sure to re-read the readme snail
> 
> Is there no limiter function anymore? like to grab only one randomly from a type?

I will open an issue, thanks 🦀
