### ISSUE TITLE
CORS error while calling from js

### ISSUE THREAD

**Issue by alaksandarjesus** [UltiRequiem/joke-api#40]
I am getting cors error while calling from javascript

![image](https://user-images.githubusercontent.com/4712552/177827290-842805f9-a661-4d7e-b0e8-9c46dea3fa99.png)

**Comment by UltiRequiem** [comment]
Could you share your code?

**Comment by UltiRequiem** [comment]
Try this 👇

```js
const response = await fetch("https://joke.deno.dev")
const body = await response.json()
console.log(body)
```

I will make an example website using the API later ✨

**Comment by alaksandarjesus** [comment]
I just tried it. If you prefer you can use the code from https://github.com/alaksandarjesus/jokes

**Comment by UltiRequiem** [comment]
![image](https://user-images.githubusercontent.com/71897736/179133925-6c7e58d1-49ac-4328-a209-fea77771eb93.png)
https://github.com/alaksandarjesus/jokes/blob/main/script.js#L67

Good job!
